name: CD

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache NuGet Packages
      id: nuget-packages
      uses: actions/cache@v3
      env:
        cache-name: nuget-package-cache
      with:
        path: D:\a\lc-terminal-slots\lc-terminal-slots\packages
        key: ${{ runner.os }}-${{ env.cache-name }}
    - name: Setup NuGet
      if: steps.nuget-packages.outputs.cache-hit != 'true'
      uses: NuGet/setup-nuget@v1.2.0
    - name: NuGet Restore
      if: steps.nuget-packages.outputs.cache-hit != 'true'
      run: nuget restore LCTerminalSlots.sln
    - name: Cache NuGet Packages
      if: steps.nuget-packages.outputs.cache-hit != 'true'
      id: nuget-packages-backup
      uses: actions/cache@v3
      env:
        cache-name: nuget-package-cache
      with:
        path: D:\a\lc-terminal-slots\lc-terminal-slots\packages
        key: ${{ runner.os }}-${{ env.cache-name }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore Dependencies
      if: steps.nuget-packages.outputs.cache-hit != 'true'
      run: dotnet restore
    - name: Build DLL
      run: dotnet build --no-restore
    - name: Test Build
      run: dotnet test --no-build --verbosity normal
