name: 'CI'

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: TestTagOutput
        run: | 
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0
      - name: NuGet Restore
        run: nuget restore LCTerminalSlots.sln
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore Dependencies
        run: dotnet restore
      - name: Build DLL
        run: dotnet build --no-restore
      - name: Test Build
        run: dotnet test --no-build --verbosity normal
